"""initial schema

Revision ID: b408056eb34b
Revises: 
Create Date: 2026-07-25 22:46:10.200413
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b408056eb34b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('line_name', sa.String(length=120), nullable=True),
    sa.Column('prev_station_code', sa.String(length=10), nullable=False),
    sa.Column('prev_station_name', sa.String(length=120), nullable=True),
    sa.Column('next_station_code', sa.String(length=10), nullable=False),
    sa.Column('next_station_name', sa.String(length=120), nullable=True),
    sa.Column('distance_from_prev_km', sa.Float(), nullable=False),
    sa.Column('distance_from_next_km', sa.Float(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('approach_distance_km', sa.Float(), nullable=False),
    sa.Column('min_close_lead_seconds', sa.Integer(), nullable=False),
    sa.Column('max_close_lead_seconds', sa.Integer(), nullable=False),
    sa.Column('reopen_lag_seconds', sa.Integer(), nullable=False),
    sa.Column('min_gate_cycle_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crossings'))
    )
    with op.batch_alter_table('crossings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crossings_next_station_code'), ['next_station_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_crossings_prev_station_code'), ['prev_station_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_crossings_slug'), ['slug'], unique=True)

    op.create_table('calibration_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('train_class', sa.String(length=24), nullable=False),
    sa.Column('pass_offset_seconds', sa.Float(), nullable=False),
    sa.Column('close_offset_seconds', sa.Float(), nullable=False),
    sa.Column('open_offset_seconds', sa.Float(), nullable=False),
    sa.Column('pass_mae_seconds', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_sample_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_calibration_profiles_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_profiles')),
    sa.UniqueConstraint('crossing_id', 'train_class', name=op.f('uq_calibration_profiles_crossing_id'))
    )
    op.create_table('closure_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('causes', sa.JSON(), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_closure_windows_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_closure_windows'))
    )
    with op.batch_alter_table('closure_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closure_windows_close_at'), ['close_at'], unique=False)
        batch_op.create_index('ix_window_crossing_time', ['crossing_id', 'close_at'], unique=False)

    op.create_table('gate_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_hash', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_gate_reports_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gate_reports'))
    )
    with op.batch_alter_table('gate_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gate_reports_reported_at'), ['reported_at'], unique=False)
        batch_op.create_index('ix_report_crossing_time', ['crossing_id', 'reported_at'], unique=False)

    op.create_table('notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('lead_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_notification_subscriptions_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_notification_subscriptions_endpoint'))
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=12), nullable=True),
    sa.Column('train_class', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('observed_pass_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_unexplained', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_observations_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_crossing_time', ['crossing_id', 'observed_pass_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_is_unexplained'), ['is_unexplained'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_train_number'), ['train_number'], unique=False)

    op.create_table('sighting_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=12), nullable=False),
    sa.Column('train_name', sa.String(length=120), nullable=True),
    sa.Column('train_type', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_trust', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_to_crossing_km', sa.Float(), nullable=True),
    sa.Column('speed_kmph', sa.Float(), nullable=True),
    sa.Column('is_actual_position', sa.Boolean(), nullable=False),
    sa.Column('estimated_pass_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_sighting_snapshots_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sighting_snapshots'))
    )
    with op.batch_alter_table('sighting_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_sighting_crossing_time', ['crossing_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sighting_snapshots_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index('ix_sighting_train', ['crossing_id', 'train_number', 'observed_at'], unique=False)

    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=12), nullable=False),
    sa.Column('train_name', sa.String(length=120), nullable=False),
    sa.Column('train_type', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('scheduled_pass_minute', sa.Integer(), nullable=False),
    sa.Column('run_days', sa.String(length=7), nullable=False),
    sa.Column('typical_speed_kmph', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_timetable_entries_crossing_id_crossings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_entries')),
    sa.UniqueConstraint('crossing_id', 'train_number', 'scheduled_pass_minute', name=op.f('uq_timetable_entries_crossing_id'))
    )
    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetable_entries_train_number'), ['train_number'], unique=False)
        batch_op.create_index('ix_timetable_lookup', ['crossing_id', 'scheduled_pass_minute'], unique=False)

    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crossing_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=12), nullable=False),
    sa.Column('train_class', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_pass_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_seconds', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('pass_error_seconds', sa.Float(), nullable=True),
    sa.Column('close_error_seconds', sa.Float(), nullable=True),
    sa.Column('open_error_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossings.id'], name=op.f('fk_prediction_records_crossing_id_crossings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_prediction_records_observation_id_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_records'))
    )
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.create_index('ix_pred_match', ['crossing_id', 'train_number', 'predicted_pass_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_graded'), ['graded'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_predicted_at'), ['predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_train_class'), ['train_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_train_number'), ['train_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_records_train_number'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_train_class'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_predicted_at'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_graded'))
        batch_op.drop_index('ix_pred_match')

    op.drop_table('prediction_records')
    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_timetable_lookup')
        batch_op.drop_index(batch_op.f('ix_timetable_entries_train_number'))

    op.drop_table('timetable_entries')
    with op.batch_alter_table('sighting_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_sighting_train')
        batch_op.drop_index(batch_op.f('ix_sighting_snapshots_observed_at'))
        batch_op.drop_index('ix_sighting_crossing_time')

    op.drop_table('sighting_snapshots')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_train_number'))
        batch_op.drop_index(batch_op.f('ix_observations_is_unexplained'))
        batch_op.drop_index('ix_obs_crossing_time')

    op.drop_table('observations')
    op.drop_table('notification_subscriptions')
    with op.batch_alter_table('gate_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_report_crossing_time')
        batch_op.drop_index(batch_op.f('ix_gate_reports_reported_at'))

    op.drop_table('gate_reports')
    with op.batch_alter_table('closure_windows', schema=None) as batch_op:
        batch_op.drop_index('ix_window_crossing_time')
        batch_op.drop_index(batch_op.f('ix_closure_windows_close_at'))

    op.drop_table('closure_windows')
    op.drop_table('calibration_profiles')
    with op.batch_alter_table('crossings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crossings_slug'))
        batch_op.drop_index(batch_op.f('ix_crossings_prev_station_code'))
        batch_op.drop_index(batch_op.f('ix_crossings_next_station_code'))

    op.drop_table('crossings')
    # ### end Alembic commands ###
